server:
  port: 9000

spring:
  datasource:
    a-database: # 主数据源
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: ''
      driver-class-name: com.mysql.cj.jdbc.Driver
    b-database: # 从数据源
      url: jdbc:mysql://localhost:3306/blog_user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: ''
      driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
#      连接池名
      pool-name: DateHikariCP
#      最小
      minimum-idle: 5
#      空闲连接最大存活时间默认600000（10分钟）
      idle-timeout: 180000
#      最大连接数
      maximum-pool-size: 10
#      从连接池返回的连接自动提交
      auto-commit: true
#      连接最大存活时间，0永久 默认1800000（30分钟）
      max-lifetime: 1800000
#      连接超时时间，默认30000（30秒）
      connection-timeout: 3000
#      测试连接是否可用的查询语句
      connection-test-query: SELECT 1
#  # rabbitmq配置
#  rabbitmq:
#    # 用户名
#    username: guest
#    # 密码
#    password: guest
#    # 服务器地址
#    host: 39.102.65.157
#    # 端口
#    port: 5672
#    # 消息失败回调
#    publisher-returns: true
#    # 消息确认回调
#    publisher-confirm-type: correlated

  redis:
    timeout: 10000ms
    host: 127.0.0.1
    port: 6379
    database: 15 # 选择哪个库，默认0库
    lettuce:
      pool:
        max-active: 1024 # 最大连接数，默认 8
        max-wait: 10000ms # 最大连接阻塞等待时间，单位毫秒，默认 -1
        max-idle: 200 # 最大空闲连接，默认 8
        min-idle: 5

mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置mybatis数据返回类型别名
  type-aliases-package: com.wang.server.entity
  configuration:
    # 自动驼峰命名
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL语句

#logging:
#  level:
#    com.xxxx.server.mapper: debug

jwt:
  # Jwt存储的请求头
  tokenHeader: Authorization
  # Jwt加密秘钥
  secret: yeb-secret
  # Jwt 的超期限时间（60*60）*24（24小时）
  expiration: 604800
  # Jwt负载中拿到开头
  tokenHead: Bearer

upload:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    accessKeyId: IDLTAI5tGJA7byAVhycyEDAj79
    accessKeySecret: SecretdetRBHVwtlPrIqLcb9Kuog0DdEixM9
    bucketName: junjunblog

